[package]
name = "tlock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
sha2 = "0.9"
rand = "0.8.5"
group = "0.12"
async-std = { version = "1.10.0" }
bls12_381_plus = { version = "0.7.0", features = ["nightly"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
unsigned-varint = { version = "0.7", features = [
    "futures",
    "asynchronous_codec",
] }
tracing = "0.1.36"
itertools = "0.10.5"

[dev-dependencies]
criterion = "0.4.0"
drand_core = "0.0.2"
hex = "0.4"
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "lock_unlock"
harness = false

[[bench]]
name = "encrypt_decrypt"
harness = false