[package]
name = "tlock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bls12_381_plus = { version = "0.7.0", features = ["nightly"] }
group = "0.12"
itertools = "0.10.5"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
tracing = "0.1.37"
unsigned-varint = { version = "0.7", features = [
    "futures",
    "asynchronous_codec",
] }

[target.'cfg(wasm32)'.dependencies]
getrandom = { version = "0.2.8", features = ["js"] }

[dev-dependencies]
criterion = "0.4.0"
drand_core = "0.0.4"
hex = "0.4"
tokio = { version = "1", default-features = false, features = ["macros", "rt-multi-thread"] }

[[bench]]
name = "encrypt_decrypt"
harness = false
