[package]
name = "tlock_age"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "0.9.0" }
age-core = "0.9.0"
anyhow = "1.0.69"
hex = "0.4.3"
tlock = { path = "../tlock" }

[dev-dependencies]
criterion = "0.4.0"
drand_core = "0.0.4"
rand = "0.8.5"
tokio = "1.26.0"

[features]
armor = ["age/armor"]

[[bench]]
name = "encrypt_decrypt"
harness = false